### ISSUE TITLE
非常感谢你的这些starter，加油，希望越来越丰富

### ISSUE THREAD

**Issue by leguang** [xkcoding/magic-starter#1]
非常感谢你的这些starter，加油，希望越来越丰富

**Comment by leguang** [comment]
不过给个建议，在制作starter的时候，尽量避免额外的依赖。比如我想用你的magic-starter-oss，但是我发现里面又依赖了magic-core-tool，所以我必须也得引入这些，而magic-starter-oss里面可能仅仅用到了几个类而已，你看是不是考虑每一个starter尽量独立。

**Comment by xkcoding** [comment]
感谢建议，其实我这里把 magic-core-tool 当成了个 base 依赖。。目前好像独立不出去，如果独立出去，就包含太多重复代码啦。
